config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users, except: [:new]
  root 'pages#home'
  get 'about', to:'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small> Copyright &copy; your Website</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name,msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%=msg%>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<%end%>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class:"navbar-brand", id:"logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in?%>
            <%= link_to "Create new article", new_article_path,class:"dropdown-item"%>
          <%end%>
          <%= link_to "View articles", articles_path,class:"dropdown-item"%>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Bloggers", users_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class:"nav-link"  %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin?%>
            <%= link_to "Create new Category", new_category_path,class:"dropdown-item"%>
          <%end%>
          <%= link_to "View Categories", categories_path,class:"dropdown-item"%>
        </div>
      </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %>Profile[<%= current_user.username%>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user),class:"dropdown-item"%>
            <%= link_to "Edit your profile", edit_user_path(current_user),class:"dropdown-item"%>
           <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path,class:"nav-link", method: :delete %>
        </li>
      <%else%>
        <li class="nav-item">
          <%= link_to "Log in", login_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path,class:"nav-link" %>
        </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body  class="d-flex flex-column">
    <%= render 'layouts/navigation'%>
    <div id="page-content">
    <%= render 'layouts/messages'%>
    <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>